(async () => {
  try {
    console.log('msg 1')
    console.log('msg 2')
  }
  catch (err) {
    console.log(err.message)
  }
})()
